### ISSUE TITLE
找不到指定模块

### ISSUE THREAD

**Issue by tuyazuo** [sniper00/lua_timer#1]
@sniper00 
我用你项目提供的build文件，使用vs2015 和 vs2017编译，编出来的dll都没法用，提示从timer.dll中找不到指定模块，能给些帮助吗？

**Comment by sniper00** [comment]
你有 lua53.dll 吗

**Comment by tuyazuo** [comment]
有的，我试过在正常项目中使用，然后只用lua解释器运行，都发生同样的错误

**Comment by sniper00** [comment]
设置下 lua 的动态库搜索目录

**Comment by tuyazuo** [comment]
[lua_53.zip](https://github.com/sniper00/lua_timer/files/864490/lua_53.zip)

我看目录是正确的，我这有个简单例子，能不能帮我看下，thanks

**Comment by sniper00** [comment]
我上传了示例，你自己编译试下

**Comment by tuyazuo** [comment]
我做了些其他测试，发现是编译出来的dll不可用，我用的是vs2017 编译64位（vs2015也是一样），这个有测试过吗，或者你有编译好的dll吗，发我一个测试下，thanks

**Comment by sniper00** [comment]
我上传的工程，里面有示例。

**Comment by sniper00** [comment]
你的估计编译环境不一致 ， 你用我上传的，编译完后你把  example目录示例 拷贝到 bin/debug (release) 目录下，用里面的lua.exe 运行

**Comment by tuyazuo** [comment]
thanks终于弄明白问题了，你的timer.dll依赖你项目中的lua53.dll 我直接拿timer和我自己编译的lua.dll用，导致无法加载依赖的dll！ 对c++和编译这些东西不熟悉，踩坑了......

**Comment by sniper00** [comment]
你可以自己修改VS工程，设置 timer 依赖的lua 动态库
